//=========================================================================================
//This function handles frontend logic to use gemini to fill out the create listing form for the user
// Generated by Gemini
// @author https://gemini.google.com/
//==========================================================================================

// --- DOM ELEMENTS ---
const sendBtn = document.getElementById('sendAiMessage');
const chatInput = document.getElementById('aiUserInput');
const chatWindow = document.getElementById('aiChatWindow');
const sidebar = document.getElementById("aiSidebar");
const openBtn = document.getElementById("aiToggleButton");
const closeBtn = document.getElementById("closeAiSidebar");

// --- SIDEBAR TOGGLE ---
openBtn.addEventListener("click", () => {
    sidebar.classList.remove("translate-x-full");
    openBtn.style.opacity = "0";
    openBtn.style.pointerEvents = "none";
});

closeBtn.addEventListener("click", () => {
    sidebar.classList.add("translate-x-full");
    openBtn.style.opacity = "1";
    openBtn.style.pointerEvents = "auto";
});

// --- CHAT FUNCTIONS ---

// 1. Function to show text in the chat sidebar
function appendMessage(role, text) {
    const msgDiv = document.createElement('div');
    msgDiv.className = `flex flex-col gap-1 ${role === 'user' ? 'items-end ml-auto' : 'items-start mr-auto'} max-w-[85%] mb-4`;
    
    const bubbleClass = role === 'user' 
        ? 'bg-[#a07564] text-white rounded-tr-none' 
        : 'bg-white border border-stone-200 text-stone-800 rounded-tl-none';

    msgDiv.innerHTML = `
        <div class="${bubbleClass} p-3 rounded-2xl shadow-sm text-sm">
            ${text}
        </div>
    `;
    chatWindow.appendChild(msgDiv);
    chatWindow.scrollTop = chatWindow.scrollHeight;
}

// 2. THE INTERPRETER: This takes Gemini's response and updates your form
function processAiResponse(rawText) {
    // Check if the response contains the [UPDATE_FORM] command
    if (rawText.includes("[UPDATE_FORM]")) {
        const parts = rawText.split("[UPDATE_FORM]");
        const textToDisplay = parts[0]; // The friendly message
        const jsonString = parts[1];    // The actual form data

        appendMessage('assistant', textToDisplay);

        try {
            const data = JSON.parse(jsonString.trim());

            // Fill standard text fields
            if (data.title) document.getElementById('editTitle').value = data.title;
            if (data.location) document.getElementById('editLocation').value = data.location;
            if (data.price) document.getElementById('editPrice').value = data.price;
            if (data.description) document.getElementById('editDescription').value = data.description;
            if (data.contact) document.getElementById('editContact').value = data.contact;

            // Handle Categories (Checkboxes)
            if (data.category && Array.isArray(data.category)) {
                // Map names in prompt to your specific IDs
                const catMap = {
                    "Produce": "editProduce",
                    "Meat": "editMeat",
                    "Dairy": "editDairy",
                    "Baked Goods": "editBakedGoods",
                    "Cooked Meals": "editCookedMeals"
                };
                data.category.forEach(catName => {
                    const id = catMap[catName];
                    if (id) document.getElementById(id).checked = true;
                });
            }

            // Handle multiple foods (Dynamic Rows)
            if (data.foods && Array.isArray(data.foods)) {
                const list = document.getElementById('foodsList');
                list.innerHTML = ''; // Clear current items
                data.foods.forEach(item => {
                    // This calls your existing function that adds a new row to the DOM
                    if (typeof addFoodRow === 'function') {
                        addFoodRow(item.name, item.quantity);
                    }
                });
            }

        } catch (e) {
            console.error("Failed to parse AI JSON:", e);
        }
    } else {
        // Just a normal conversation message
        appendMessage('assistant', rawText);
    }
}

// 3. MAIN SEND FUNCTION
async function handleChat() {
    const message = chatInput.value.trim();
    if (!message) return;

    appendMessage('user', message);
    chatInput.value = '';

    const loadingId = 'ai-loading-' + Date.now();
    const loadingDiv = document.createElement('div');
    loadingDiv.id = loadingId;
    loadingDiv.className = "text-xs text-stone-400 italic ml-2 mb-4";
    loadingDiv.innerText = "Pantry Swap is thinking...";
    chatWindow.appendChild(loadingDiv);

    // Option A: Scraping the form for context
    const formData = {
        title: document.getElementById('editTitle').value,
        location: document.getElementById('editLocation').value,
        price: document.getElementById('editPrice').value,
        description: document.getElementById('editDescription').value,
        contact: document.getElementById('editContact').value
    };

    try {
        const response = await fetch('/api/chat', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ message, formData })
        });

        const data = await response.json();
        
        const loadingEl = document.getElementById(loadingId);
        if (loadingEl) loadingEl.remove();

        if (data.text) {
            processAiResponse(data.text);
        } else {
            appendMessage('assistant', "I received an empty response. Please try again.");
        }
    } catch (error) {
        const loadingEl = document.getElementById(loadingId);
        if (loadingEl) loadingEl.innerText = "Error: Connection lost.";
        console.error("Chat Error:", error);
    }
}

// --- LISTENERS ---
sendBtn.addEventListener('click', handleChat);
chatInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') handleChat();
});







document.getElementById("cancelButton").addEventListener("click", () => {
  window.location.href = "/sell";
});

document.getElementById("addFoodBtn").addEventListener("click", () => {
  const foodsList = document.getElementById("foodsList");
  const foodRow = document.createElement("div");
  foodRow.classList.add("flex", "gap-4", "items-center");
  foodRow.innerHTML = `
        <input class="border-[#9b9b9b] flex-1 placeholder-[#d8c3bb]" type="text" placeholder="Food name" name="foodName">
        <input class="border-[#9b9b9b] w-24 placeholder-[#d8c3bb]" type="number" placeholder="Qty" min="1" name="foodQty">
        <button type="button" class="text-red-500 font-bold px-2">✕</button>
    `;
  foodRow
    .querySelector("button")
    .addEventListener("click", () => foodRow.remove());
  foodsList.appendChild(foodRow);
});

document.getElementById("saveButton").addEventListener("click", async () => {
  const updatedTitle = document.getElementById("editTitle").value;
  const updatedLocation = document.getElementById("editLocation").value;
  const updatedPrice = document.getElementById("editPrice").value;
  const updatedContact = document.getElementById("editContact").value;
  const updatedDescription = document.getElementById("editDescription").value;
  const updatedProduce = document.getElementById("editProduce").checked;
  const updatedMeat = document.getElementById("editMeat").checked;
  const updatedDairy = document.getElementById("editDairy").checked;
  const updatedBakedGoods = document.getElementById("editBakedGoods").checked;
  const updatedCookedMeals =
    document.getElementById("editCookedMeals").checked;

  const updatedCategory = [];
  if (updatedProduce) updatedCategory.push("Produce");
  if (updatedMeat) updatedCategory.push("Meat");
  if (updatedDairy) updatedCategory.push("Dairy");
  if (updatedBakedGoods) updatedCategory.push("Baked Goods");
  if (updatedCookedMeals) updatedCategory.push("Cooked Meals");

  const foods = [];
  for (const row of document.getElementById("foodsList").children) {
    const name = row.querySelector('[name="foodName"]').value;
    const quantity = row.querySelector('[name="foodQty"]').value;
    if (name) foods.push({ name, quantity: Number(quantity) });
  }

  const response = await fetch("/CreateListing", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      title: updatedTitle,
      location: updatedLocation,
      price: updatedPrice,
      contact: updatedContact,
      description: updatedDescription,
      category: updatedCategory,
      foods: foods,
    }),
  });
  if (response.ok) {
    alert("Listing created!");
  }
});
